select RegisteredCostumerUsernames.CostumerUsername,  creditWithGift.CostumerCredit - RegisteredCostumer.CostumerCredit as gift
from creditWithGift, RegisteredCostumerUsernames, RegisteredCostumer
where RegisteredCostumerUsernames.CostumerID = RegisteredCostumer.CostumerID and RegisteredCostumer.CostumerID = creditWithGift.CostumerID